-- Test schema for alerts-service tests on H2 (PostgreSQL mode).
-- Only the alert_rules table is needed — AlertEvaluator tests use a mock
-- JdbcTemplate so the rollup + incident tables don't have to exist here.

drop table if exists alert_rule_revisions;
drop table if exists alert_rules;

create table alert_rules (
    rule_id           bigint generated by default as identity primary key,
    site_id           varchar(128) not null,
    name              varchar(255) not null,
    event_type        varchar(64) not null,
    geo_level         varchar(16) not null default 'GLOBAL',
    geo_area_id       varchar(128),
    granularity       varchar(8) not null default '5m',
    threshold         bigint not null,
    comparator        varchar(2) not null default '>=',
    cooldown_seconds  integer not null default 1800,
    enabled           boolean not null default true,
    version           integer not null default 1,
    created_at        timestamp not null default current_timestamp,
    updated_at        timestamp not null default current_timestamp
);

create table alert_rule_revisions (
    revision_id   bigint generated by default as identity primary key,
    rule_id       bigint,
    version       integer not null,
    action        varchar(32) not null,
    actor         varchar(255),
    reason        varchar(1024),
    request_id    varchar(255),
    before_state  clob,
    after_state   clob,
    created_at    timestamp not null default current_timestamp
);
