-- Test schema for alerts-service tests on H2 (PostgreSQL mode).
-- Only the alert_rules table is needed — AlertEvaluator tests use a mock
-- JdbcTemplate so the rollup + incident tables don't have to exist here.

drop table if exists alert_rules;

create table alert_rules (
    rule_id           bigint generated by default as identity primary key,
    site_id           varchar(128) not null,
    name              varchar(255) not null,
    event_type        varchar(64) not null,
    geo_level         varchar(16) not null default 'GLOBAL',
    geo_area_id       varchar(128),
    granularity       varchar(8) not null default '5m',
    threshold         bigint not null,
    comparator        varchar(2) not null default '>=',
    cooldown_seconds  integer not null default 1800,
    enabled           boolean not null default true,
    created_at        timestamp not null default current_timestamp,
    updated_at        timestamp not null default current_timestamp
);
