-- ============================================================================
-- analytics-aggregator-service — V3: seed common-country centroids so the
-- visitor-globe markers endpoint can return lat/lng for backfilled rows.
-- These are approximate population-weighted centroids from GeoNames; the
-- actual rendering is just a globe pin, so sub-degree accuracy is fine.
-- ============================================================================

insert into public.geo_areas (geo_area_id, geo_level, parent_id, name, country, region, center_lat, center_lng) values
    ('COUNTRY:CN', 'COUNTRY', 'GLOBAL', 'China',                 'CN', null,  35.86,  104.20),
    ('COUNTRY:IN', 'COUNTRY', 'GLOBAL', 'India',                 'IN', null,  20.59,   78.96),
    ('COUNTRY:JP', 'COUNTRY', 'GLOBAL', 'Japan',                 'JP', null,  36.20,  138.25),
    ('COUNTRY:KR', 'COUNTRY', 'GLOBAL', 'South Korea',           'KR', null,  35.91,  127.77),
    ('COUNTRY:GB', 'COUNTRY', 'GLOBAL', 'United Kingdom',        'GB', null,  55.38,   -3.43),
    ('COUNTRY:DE', 'COUNTRY', 'GLOBAL', 'Germany',               'DE', null,  51.17,   10.45),
    ('COUNTRY:FR', 'COUNTRY', 'GLOBAL', 'France',                'FR', null,  46.23,    2.21),
    ('COUNTRY:CA', 'COUNTRY', 'GLOBAL', 'Canada',                'CA', null,  56.13, -106.35),
    ('COUNTRY:AU', 'COUNTRY', 'GLOBAL', 'Australia',             'AU', null, -25.27,  133.78),
    ('COUNTRY:BR', 'COUNTRY', 'GLOBAL', 'Brazil',                'BR', null, -14.24,  -51.93),
    ('COUNTRY:RU', 'COUNTRY', 'GLOBAL', 'Russia',                'RU', null,  61.52,  105.32),
    ('COUNTRY:MX', 'COUNTRY', 'GLOBAL', 'Mexico',                'MX', null,  23.63, -102.55),
    ('COUNTRY:ES', 'COUNTRY', 'GLOBAL', 'Spain',                 'ES', null,  40.46,   -3.75),
    ('COUNTRY:IT', 'COUNTRY', 'GLOBAL', 'Italy',                 'IT', null,  41.87,   12.57),
    ('COUNTRY:NL', 'COUNTRY', 'GLOBAL', 'Netherlands',           'NL', null,  52.13,    5.29),
    ('COUNTRY:SE', 'COUNTRY', 'GLOBAL', 'Sweden',                'SE', null,  60.13,   18.64),
    ('COUNTRY:FI', 'COUNTRY', 'GLOBAL', 'Finland',               'FI', null,  61.92,   25.75),
    ('COUNTRY:SG', 'COUNTRY', 'GLOBAL', 'Singapore',             'SG', null,   1.35,  103.82),
    ('COUNTRY:HK', 'COUNTRY', 'GLOBAL', 'Hong Kong',             'HK', null,  22.32,  114.17),
    ('COUNTRY:TW', 'COUNTRY', 'GLOBAL', 'Taiwan',                'TW', null,  23.70,  120.96),
    ('COUNTRY:ID', 'COUNTRY', 'GLOBAL', 'Indonesia',             'ID', null,  -0.79,  113.92),
    ('COUNTRY:TH', 'COUNTRY', 'GLOBAL', 'Thailand',              'TH', null,  15.87,  100.99),
    ('COUNTRY:VN', 'COUNTRY', 'GLOBAL', 'Vietnam',               'VN', null,  14.06,  108.28),
    ('COUNTRY:PH', 'COUNTRY', 'GLOBAL', 'Philippines',           'PH', null,  12.88,  121.77),
    ('COUNTRY:MY', 'COUNTRY', 'GLOBAL', 'Malaysia',              'MY', null,   4.21,  101.98),
    ('COUNTRY:NZ', 'COUNTRY', 'GLOBAL', 'New Zealand',           'NZ', null, -40.90,  174.89),
    ('COUNTRY:AR', 'COUNTRY', 'GLOBAL', 'Argentina',             'AR', null, -38.42,  -63.62),
    ('COUNTRY:CL', 'COUNTRY', 'GLOBAL', 'Chile',                 'CL', null, -35.68,  -71.54),
    ('COUNTRY:CO', 'COUNTRY', 'GLOBAL', 'Colombia',              'CO', null,   4.57,  -74.30),
    ('COUNTRY:ZA', 'COUNTRY', 'GLOBAL', 'South Africa',          'ZA', null, -30.56,   22.94),
    ('COUNTRY:EG', 'COUNTRY', 'GLOBAL', 'Egypt',                 'EG', null,  26.82,   30.80),
    ('COUNTRY:NG', 'COUNTRY', 'GLOBAL', 'Nigeria',               'NG', null,   9.08,    8.68),
    ('COUNTRY:AE', 'COUNTRY', 'GLOBAL', 'United Arab Emirates',  'AE', null,  23.42,   53.85),
    ('COUNTRY:SA', 'COUNTRY', 'GLOBAL', 'Saudi Arabia',          'SA', null,  23.89,   45.08),
    ('COUNTRY:TR', 'COUNTRY', 'GLOBAL', 'Turkey',                'TR', null,  38.96,   35.24),
    ('COUNTRY:PL', 'COUNTRY', 'GLOBAL', 'Poland',                'PL', null,  51.92,   19.15),
    ('COUNTRY:CZ', 'COUNTRY', 'GLOBAL', 'Czech Republic',        'CZ', null,  49.82,   15.47),
    ('COUNTRY:CH', 'COUNTRY', 'GLOBAL', 'Switzerland',           'CH', null,  46.82,    8.23),
    ('COUNTRY:AT', 'COUNTRY', 'GLOBAL', 'Austria',               'AT', null,  47.52,   14.55),
    ('COUNTRY:BE', 'COUNTRY', 'GLOBAL', 'Belgium',               'BE', null,  50.50,    4.47),
    ('COUNTRY:DK', 'COUNTRY', 'GLOBAL', 'Denmark',               'DK', null,  56.26,    9.50),
    ('COUNTRY:NO', 'COUNTRY', 'GLOBAL', 'Norway',                'NO', null,  60.47,    8.47),
    ('COUNTRY:IE', 'COUNTRY', 'GLOBAL', 'Ireland',               'IE', null,  53.41,   -8.24),
    ('COUNTRY:PT', 'COUNTRY', 'GLOBAL', 'Portugal',              'PT', null,  39.40,   -8.22),
    ('COUNTRY:GR', 'COUNTRY', 'GLOBAL', 'Greece',                'GR', null,  39.07,   21.82),
    ('COUNTRY:IL', 'COUNTRY', 'GLOBAL', 'Israel',                'IL', null,  31.05,   34.85),
    ('COUNTRY:PK', 'COUNTRY', 'GLOBAL', 'Pakistan',              'PK', null,  30.38,   69.35),
    ('COUNTRY:BD', 'COUNTRY', 'GLOBAL', 'Bangladesh',            'BD', null,  23.68,   90.36),
    ('COUNTRY:UA', 'COUNTRY', 'GLOBAL', 'Ukraine',               'UA', null,  48.38,   31.17),
    ('COUNTRY:RO', 'COUNTRY', 'GLOBAL', 'Romania',               'RO', null,  45.94,   24.97),
    ('COUNTRY:HU', 'COUNTRY', 'GLOBAL', 'Hungary',               'HU', null,  47.16,   19.50)
on conflict (geo_area_id) do nothing;
